#!/bin/bash

if [ ! -f ./target/credit_simulator-1.0-SNAPSHOT-jar-with-dependencies.jar ]; then
    ./mvnw clean package
fi

java -jar ./target/credit_simulator-1.0-SNAPSHOT-jar-with-dependencies.jar $1 $2 $3 $4 $5 $6 $7 $8 $9